[phases.setup]
aptPkgs = [
  "php",
  "php-cli",
  "php-mbstring",
  "php-xml",
  "php-curl",
  "php-mysql",
  "php-zip",
  "php-bcmath",
  "php-gd"
]

[phases.build]
cmds = [
  "composer install --no-dev --optimize-autoloader"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"
